<a href="https://colab.research.google.com/github/19PA1A0283/AI-Lab/blob/master/Experiment_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1) Experiment 1:Numpy

##i) Different ways to create Numpy arrays

In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


##ii)Add,remove,modify array elements

###a)Add

In [3]:
a=np.array([5,6,7])
b=np.append(a,[4,8,9])
print(b)

[5 6 7 4 8 9]


###b)remove

In [4]:
c=np.delete(a,2)
print(c)

[5 6]


###c)modify

In [5]:
c[c>5]=-1
print(c)

[ 5 -1]


##iii)Arthematic operations on numpy array

In [7]:
import numpy as np
s=np.random.random((6,6))
m=np.random.random((6,6))
num_sum=np.add(s,m)
num_diff=np.subtract(s,m)
num_prod=np.multiply(s,m)
num_quo=np.divide(s,m)
num_mod=np.mod(s,m)
num_pow=np.power(s,m)
print(num_sum)
print(num_diff)
print(num_prod)
print(num_quo)
print(num_mod)
print(num_pow)

[[0.8678347  0.92801057 0.68137095 1.32914892 1.2361926  0.92192097]
 [1.01217715 0.64513328 0.81641847 1.2350608  1.06577991 1.12086715]
 [0.66575073 0.50592588 0.91820699 1.86248708 1.58730771 1.61643921]
 [1.26841824 0.55139284 1.22366974 0.67026337 1.66462196 1.24390039]
 [1.05129947 0.42731202 0.91585257 0.39887433 1.0981874  1.78150766]
 [0.20240271 1.07380896 0.30385694 1.09768865 0.98189701 0.87583455]]
[[ 0.5297468   0.64919674 -0.47931652 -0.66085732 -0.21545523  0.03244176]
 [ 0.81621603  0.24064404 -0.28529296  0.11452554  0.05414076 -0.70656042]
 [-0.26087773  0.23371101 -0.10793535 -0.11130794 -0.15416824  0.03847396]
 [ 0.3679546  -0.12901486 -0.71091493  0.56400385  0.19630872  0.66733443]
 [ 0.52557003 -0.12155021 -0.39488968  0.39220021 -0.30884744  0.07315377]
 [ 0.07333491  0.19135519 -0.05388532 -0.03920251 -0.36578862 -0.67739982]]
[[0.11812635 0.1099368  0.05863051 0.33247611 0.3704378  0.21222145]
 [0.08957349 0.08957185 0.14628676 0.37806477 0.2832389  0.189278

##iv)slicing and iterating of numpy arrays

###a)slicing

In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[2:7])

[3 4 5 6 7]


###b)iterating

In [11]:
for x in arr:
  print(x)

1
2
3
4
5
6
7
8


##v)matrix operations on numpy arrays

In [12]:
import numpy as np
s=np.array([[1,4],[3,2]])
m=np.array([[5,7],[6,8]])
print(np.add(s,m))
print(np.subtract(s,m))
print(np.divide(s,m))

[[ 6 11]
 [ 9 10]]
[[-4 -3]
 [-3 -6]]
[[0.2        0.57142857]
 [0.5        0.25      ]]
